# fly.toml app configuration file generated for brizdoors-app-v0-1 on 2025-07-06T20:27:08+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'brizdoors-app-v0-1'
primary_region = 'syd'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
